service: remindMe

provider:
  name: aws
  runtime: nodejs16.x
  # stage: stage, 'dev'
  # region: region, 'us-east-1'
  memorySize: 128
  timeout: 3


functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
  - serverless-plugin-typescript-express
  - serverless-dotenv-plugin